export const CONVERGEOS_MCP_SERVER_NAME = "convergeos";
export const LEGACY_CONVERGEOS_MCP_SERVER_NAME = "t3-code";

export const CONVERGEOS_MCP_BEARER_TOKEN_ENV = "CONVERGEOS_MCP_BEARER_TOKEN";
export const LEGACY_CONVERGEOS_MCP_BEARER_TOKEN_ENV = "T3_MCP_BEARER_TOKEN";
